import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#4f2500",
              "primary-container": "#7c3aed",
              "on-primary-fixed": "#25005a",
              "outline-variant": "#4a4455",
              "on-surface": "#e8dfee",
              "inverse-on-surface": "#332f39",
              "error-container": "#93000a",
              "bg-base": "#0A0E1A",
              "secondary-fixed-dim": "#c0c6db",
              "neon-green": "#39FF14",
              "background": "#15121b",
              "surface": "#15121b",
              "surface-container-lowest": "#100d16",
              "primary-fixed": "#eaddff",
              "bg-elevated": "#1A2235",
              "on-tertiary-fixed-variant": "#713700",
              "surface-container": "#221e28",
              "primary-fixed-dim": "#d2bbff",
              "on-primary-container": "#ede0ff",
              "secondary": "#c0c6db",
              "surface-dim": "#15121b",
              "outline": "#958da1",
              "surface-variant": "#37333e",
              "text-secondary": "#94A3B8",
              "surface-container-low": "#1d1a24",
              "brand-purple": "#7C3AED",
              "tertiary-container": "#a15100",
              "surface-container-high": "#2c2833",
              "on-secondary-fixed-variant": "#404758",
              "on-primary": "#3f008e",
              "tertiary-fixed": "#ffdcc6",
              "surface-tint": "#d2bbff",
              "inverse-primary": "#732ee4",
              "surface-container-highest": "#37333e",
              "surface-bright": "#3c3742",
              "crimson": "#EF4444",
              "tertiary-fixed-dim": "#ffb784",
              "on-tertiary-container": "#ffe0cd",
              "on-secondary-fixed": "#141b2b",
              "inverse-surface": "#e8dfee",
              "on-primary-fixed-variant": "#5a00c6",
              "bg-surface": "#111827",
              "on-error-container": "#ffdad6",
              "ember-gold": "#FFB800",
              "secondary-container": "#404758",
              "electric-blue": "#00C8FF",
              "streak-orange": "#F97316",
              "on-surface-variant": "#ccc3d8",
              "primary": "#d2bbff",
              "tertiary": "#ffb784",
              "on-tertiary-fixed": "#301400",
              "secondary-fixed": "#dce2f7",
              "on-secondary": "#293040",
              "on-secondary-container": "#aeb5c9",
              "on-background": "#e8dfee",
              "on-error": "#690005",
              "error": "#ffb4ab",
              "text-primary": "#F1F5F9"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "stack-sm": "8px",
              "hud-height": "52px",
              "gutter": "16px",
              "cta-height": "52px",
              "unit": "4px",
              "container-margin": "20px",
              "stack-lg": "32px",
              "stack-md": "16px"
      },
      "fontFamily": {
              "button-label": ["Rajdhani"],
              "h2-section": ["Rajdhani"],
              "code-snippet": ["JetBrains Mono"],
              "body-base": ["Rajdhani"],
              "h1-display": ["Orbitron"],
              "app-wordmark": ["Orbitron"],
              "hud-caption": ["Rajdhani"],
              "body-lore": ["Rajdhani"]
      },
      "fontSize": {
              "button-label": ["16px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
              "h2-section": ["20px", {"lineHeight": "1.4", "fontWeight": "700"}],
              "code-snippet": ["14px", {"lineHeight": "1.7", "fontWeight": "400"}],
              "body-base": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h1-display": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
              "app-wordmark": ["32px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "900"}],
              "hud-caption": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
              "body-lore": ["15px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
export default config;
